config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'managers/registrations',
    invitations: 'managers/invitations'
  }

  scope path: '/dashboard' do
    resources :features
    resources :plans do
      resources :subscriptions, controller: :subscriptions, shallow: true
    end

    scope module: :managers do
      get '/', to: 'dashboard#index'
      get '/invitees', to: 'dashboard#invitees', as: :invitees
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  belongs_to :manager, class_name: 'User'

  has_and_belongs_to_many :plans

  after_create :create_stripe_product
  before_update :update_stripe_product

  def create_stripe_product
    StripeServices::ProductService.create(self)
  end

  def update_stripe_product
    StripeServices::PriceService.update(self) if unit_price_changed?
    StripeServices::ProductService.update(self) if name_changed?
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :manager, class_name: 'User'

  has_and_belongs_to_many :features

  before_save :update_plan_fee

  def update_plan_fee
    self.monthly_fee = features.reduce(0) { |sum, feature| sum + feature.unit_price }
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  pay_customer
  rolify
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable, :confirmable

  belongs_to :manager, class_name: 'User', foreign_key: :invited_by_id, optional: true
  has_many :buyers, class_name: 'User', foreign_key: :invited_by_id

  # Manager associations
  has_many :features, foreign_key: 'manager_id'
  has_many :plans, foreign_key: 'manager_id'

  before_invitation_created :add_user_role

  def add_user_role
    add_role :buyer
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :authenticate_user!

  def index
    @features = policy_scope(Feature).all
  end

  def show
    @feature = policy_scope(Feature).find(params[:id])
  end

  def new
    @feature = Feature.new
    authorize @feature
  end

  def create
    @feature = current_user.features.build(feature_params)
    authorize @feature
    if @feature.save
      redirect_to @feature
    else
      render 'new'
    end
  end

  def edit
    @feature = policy_scope(Feature).find params[:id]
    authorize @feature
  end

  def update
    @feature = policy_scope(Feature).find params[:id]
    if @feature.update(feature_params)
      redirect_to @feature
    else
      render 'edit'
    end
  end

  def destroy
    authorize Feature
    Feature.find(params[:id]).destroy
    redirect_to features_path
  end

  private

  def feature_params
    params.required(:feature).permit(:name, :code, :max_unit_limit, :unit_price)
  end
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def index; end
end

app/controllers/managers/dashboard_controller.rb
class Managers::DashboardController < ApplicationController
  before_action :authenticate_user!

  def manager?
    return if current_user.has_role? :manager

    redirect_to buyers_path
  end

  def index
    @features = Feature.count
    @plans = Plan.count
    @invitees = current_user.buyers.count
  end

  def invitees
    @invitees = current_user.buyers
  end
end

app/controllers/managers/invitations_controller.rb
class Managers::InvitationsController < Devise::InvitationsController
  before_action :manager?, only: [:new, :create]

  def manager?
    return if current_user.has_role? :manager

    redirect_to root_path, alert: 'You are not authorized to perform this action.'
  end
end

app/controllers/managers/registrations_controller.rb
# frozen_string_literal: true

class Managers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |resource|
      resource.add_role :manager
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = policy_scope(Plan).includes(:features).all
  end

  def show
    @plan = policy_scope(Plan).includes(:features).find(params[:id])
  end

  def new
    @plan = Plan.new
    @features = policy_scope(Feature)
    authorize @plan
  end

  def create
    @plan = current_user.plans.build(plan_params)
    authorize @plan
    if @plan.save
      redirect_to @plan
    else
      render 'new'
    end
  end

  def edit
    @plan = Plan.find_by params[:id]
    @features = current_user.features
    authorize @plan
  end

  def update
    @plan = current_user.plans.find(params[:id])
    authorize @plan
    if @plan.update(plan_params)
      redirect_to @plan
    else
      render 'edit'
    end
  end

  def destroy
    authorize Plan
    Plan.find(params[:id]).destroy
    redirect_to plans_path
  end

  private

  def plan_params
    params.required(:plan).permit(:name, feature_ids: [])
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    current_user.set_payment_processor :stripe
    # current_user.customer
    prices = Feature.joins(:plans).where(plans: { id: params[:plan_id] }).select(:stripe_price, :stripe_metered_price,
                                                                                 :max_unit_limit)
    session = current_user.payment_processor.checkout(
      mode: 'subscription',
      line_items: [
        *prices.map { |item| { price: item.stripe_price, quantity: item.max_unit_limit } },
        *prices.map { |item| { price: item.stripe_metered_price } }
      ]
    )
    redirect_to session[:url]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/managers/dashboard_helper.rb
module Managers::DashboardHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/features/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 form-wrapper p-5 mt-5">
            <h3>Create Feature</h3>
            <%= form_for(@feature) do |f| %>

                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                <%= render "/shared/field_errors", resource: @feature, field: :name %>

                <div class="form-group">
                    <%= f.label :code %>
                    <%= f.text_field :code, class: 'form-control' %>
                </div>
                <%= render "/shared/field_errors", resource: @feature, field: :code %>

                <div class="form-group">
                    <%= f.label :max_unit_limit %>
                    <%= f.number_field :max_unit_limit, class: 'form-control' %>
                </div>
                <%= render "/shared/field_errors", resource: @feature, field: :max_unit_limit %>

                <div class="form-group">
                    <%= f.label :unit_price %>
                    <%= f.number_field :unit_price, class: 'form-control' %>
                </div>
                <%= render "/shared/field_errors", resource: @feature, field: :unit_price %>

                <%= f.submit 'Update feature', class: 'btn btn-success' %>
            <% end %>
            <h5 class="mt-3">
                <%= link_to 'Back', features_path %> | 
                <%= link_to 'Details', @feature %> | 
                <%= link_to 'delete', @feature, method: :delete %>
            </h5>
        </div>
    </div>
</div>

app/views/features/index.html.erb
<div class="card">
    <div class="card-header pb-0 px-3">
    <div class="row">
        <div class="col-6 d-flex align-items-center">
            <h6 class="mb-0">Features Inforamtion</h6>
        </div>
        <div class="col-6 text-end">
            <a class="btn btn-outline-primary btn-sm mb-0", href='<%= new_feature_path %>'>Create feature</a>
        </div>
    </div>
    </div>
    <% is_manager = current_user.has_role? :manager %>
    <div class="card-body pt-4 p-3">
        <ul class="list-group">
            <% @features.each do |feature| %>
                <li class="list-group-item border-0 d-flex p-4 mb-2 bg-gray-100 border-radius-lg">
                    <div class="d-flex flex-column">
                        <h6 class="mb-3 text-sm"><%= link_to feature.name, feature %></h6>
                        <span class="mb-2 text-xs">Feature Code: 
                            <span class="text-dark font-weight-bold ms-sm-2"><%= feature.code %></span>
                        </span>
                        <span class="mb-2 text-xs">feature Unit Price:  
                            <span class="text-dark ms-sm-2 font-weight-bold">$<%= feature.unit_price %></span>
                        </span>
                        <span class="text-xs">Owner Email: 
                            <span class="text-dark ms-sm-2 font-weight-bold"><%= feature.manager.email %></span>
                        </span>
                    </div>
                    <% if is_manager %>
                    <div class="ms-auto text-end">
                        <a class="btn btn-link text-danger text-gradient px-3 mb-0" href="<%= feature_path(feature)%>" data-method="delete">
                            <i class="far fa-trash-alt me-2" aria-hidden="true"></i> Delete
                        </a>
                        <a class="btn btn-link text-dark px-3 mb-0" href="<%= new_feature_path(feature)%>">
                            <i class="fas fa-pencil-alt text-dark me-2" aria-hidden="true"></i> Edit
                        </a>
                    </div>
                    <% end %>
                </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/features/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 form-wrapper p-5 mt-5">
            <h3>Create Feature</h3>
            <%= form_for(@feature) do |f| %>

                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                <%= render "/shared/field_errors", resource: @feature, field: :name %>

                <div class="form-group">
                    <%= f.label :code %>
                    <%= f.text_field :code, class: 'form-control' %>
                </div>
                <%= render "/shared/field_errors", resource: @feature, field: :code %>

                <div class="form-group">
                    <%= f.label :max_unit_limit %>
                    <%= f.number_field :max_unit_limit, class: 'form-control' %>
                </div>
                <%= render "/shared/field_errors", resource: @feature, field: :max_unit_limit %>

                <div class="form-group">
                    <%= f.label :unit_price %>
                    <%= f.number_field :unit_price, class: 'form-control' %>
                </div>
                <%= render "/shared/field_errors", resource: @feature, field: :unit_price %>

                <%= f.submit 'Create feature', class: 'btn btn-success' %>
            <% end %>

            <h5 class="mt-3">
                <%= link_to 'Back', features_path %>
            </h5>

        </div>
    </div>
</div>

app/views/features/show.html.erb
<h1><%= @feature.name %></h1>

<ul>
    <li>
        <b>Code: </b><%= @feature.code %> |
    </li>
    <li>
        <b>Max Unit Limit: </b><%= @feature.max_unit_limit %> |
    </li>
    <li>
        <b>Manager Id: </b><%= @feature.manager_id %> |
    </li>
    <li>
        <b>Unit Price: </b><%= @feature.unit_price %> |
    </li>
</ul>

<h5 class="mt-3">
    <%= link_to 'Back', features_path %> | 
    <% if current_user.has_role? :manager %>
        <%= link_to 'Edit', edit_feature_path(@feature) %> | 
        <%= link_to 'delete', @feature, method: :delete %>
    <% end %>
</h5>

app/views/greetings/index.html.erb
<h1>Greetings#index</h1>
<p>Find me in app/views/greetings/index.html.erb</p>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>PaymentSubscriptionSystem</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class='mh-100'>
    <div class="container mh-100">
        <div class="row mh-100 justify-content-center align-items-center">
            <div class="col-6 form-wrapper p-5">
                <%= render 'shared/notices_alerts' %>
                
                <%= yield %>
            </div>
        </div>
    </div>
</body>

</html>

app/views/managers/dashboard/index.html.erb
<div class="row">
    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
        <div class="card">
            <div class="card-body p-3">
                <div class="row">
                    <div class="col-8">
                        <div class="numbers">
                            <p class="text-sm mb-0 text-capitalize font-weight-bold">Features</p>
                            <h5 class="font-weight-bolder mb-0">
                                <%= @features %>
                                <span class="text-success text-sm font-weight-bolder">+55%</span>
                            </h5>
                        </div>
                    </div>
                    <div class="col-4 text-end">
                        <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                            <i class="ni ni-money-coins text-lg opacity-10" aria-hidden="true"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
        <div class="card">
            <div class="card-body p-3">
                <div class="row">
                    <div class="col-8">
                        <div class="numbers">
                            <p class="text-sm mb-0 text-capitalize font-weight-bold">Plans</p>
                            <h5 class="font-weight-bolder mb-0">
                                <%= @plans %>
                                <span class="text-success text-sm font-weight-bolder">+3%</span>
                            </h5>
                        </div>
                    </div>
                    <div class="col-4 text-end">
                        <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                            <i class="ni ni-world text-lg opacity-10" aria-hidden="true"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
        <div class="card">
            <div class="card-body p-3">
                <div class="row">
                    <div class="col-8">
                        <div class="numbers">
                            <p class="text-sm mb-0 text-capitalize font-weight-bold">New Clients</p>
                            <h5 class="font-weight-bolder mb-0">
                                <%= @invitees %>
                                <span class="text-danger text-sm font-weight-bolder">-2%</span>
                            </h5>
                        </div>
                    </div>
                    <div class="col-4 text-end">
                        <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                            <i class="ni ni-paper-diploma text-lg opacity-10" aria-hidden="true"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6">
        <div class="card">
            <div class="card-body p-3">
                <div class="row">
                    <div class="col-8">
                        <div class="numbers">
                            <p class="text-sm mb-0 text-capitalize font-weight-bold">Invitees</p>
                            <h5 class="font-weight-bolder mb-0">
                                $103,430
                                <span class="text-success text-sm font-weight-bolder">+5%</span>
                            </h5>
                        </div>
                    </div>
                    <div class="col-4 text-end">
                        <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                            <i class="ni ni-cart text-lg opacity-10" aria-hidden="true"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/managers/dashboard/invitees.html.erb
<h1>Invited Users</h1>
<%= link_to 'Invite New User', new_user_invitation_path %>

<ul>
    <% @invitees.each do |invitee| %>
        <li>
            <b>Name: </b><%= invitee.email %> |
            <b>Created by Invite: </b><%= invitee.created_by_invite? %> |
            <b>invitation accepted: </b><%= invitee.invitation_accepted? %> |
        </li>
    <% end %>
</ul>

app/views/plans/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 form-wrapper p-5 mt-5">
            <h3>Create Plan</h3>
            <%= form_for(@plan) do |f| %>

                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                <%= render "/shared/field_errors", resource: @plan, field: :name %>

                
                <div class="form-group">
                    <%= f.label :features %>
                    <p class="text-secondary"><small>To keep the previous features use CTRL while selecting new features:</small></p>
                    <%= f.collection_select :feature_ids, @features, :id, :name, {include_hidden: false}, {multiple: true, class: 'form-control'} %>
                </div>
                <%= render "/shared/field_errors", resource: @plan, field: :code %>

                <%= f.submit 'Update Plan', class: 'btn btn-success' %>
            <% end %>
            <h5 class="mt-3">
                <%= link_to 'Back', plans_path %> | 
                <%= link_to 'Details', @plan %> | 
                <%= link_to 'delete', @plan, method: :delete %>
            </h5>
        </div>
    </div>
</div>

app/views/plans/index.html.erb
<% is_manager = current_user.has_role? :manager %>

<h1>Plans</h1>
<% if is_manager %>
    <%= link_to 'Create Plan', new_plan_path %>
<% end %>

<ul>
    <% has_role = current_user.has_role? :manager %>
    <% @plans.each do |plan| %>
    <li>
        <b>Name: </b><%= plan.name %> |
        <b>monthly_fee: </b><%= plan.monthly_fee %> |
        <b>Name: </b><%= plan.manager_id %>
        <b>features: </b><%= plan.features.count %> |
        <b>Link to: </b><%= link_to 'Details', plan_path(plan) %> |
        <% if is_manager %>
        <%= link_to 'Edit', edit_plan_path(plan) %> |
        <%= link_to 'Delete', plan_path(plan), method: :delete %>
        <% end %>
    </li>
    <% end %>
</ul>

app/views/plans/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 form-wrapper p-5 mt-5">
            <h3>Create Plan</h3>
            <%= form_for(@plan) do |f| %>

                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                <%= render "/shared/field_errors", resource: @plan, field: :name %>

                <div class="form-group">
                    <%= f.label :features %>
                    <%= f.collection_select :feature_ids, @features, :id, :name, {include_hidden: false}, {multiple: true, class: 'form-control'} %>
                </div>
                <%= render "/shared/field_errors", resource: @plan, field: :code %>

                <%= f.submit 'Create Plan', class: 'btn btn-success' %>
            <% end %>

            <h5 class="mt-3">
                <%= link_to 'Back', plans_path %>
            </h5>

        </div>
    </div>
</div>

app/views/plans/show.html.erb
<div class="container">
    <h1><%= @plan.name %></h1>

    <ul>
        <li>
            <b>Monthly Fee: </b>$<%= @plan.monthly_fee %> |
        </li>
        <li>
            <b>Manager Id: </b><%= @plan.manager_id %> |
        </li>

        <li>
            <b>Features: </b> <br>
            <ul>
                <% @plan.features.each do |feature| %>
                    <li>
                        <b>Name: </b><%= feature.name %> |
                        <b>Code: </b><%= feature.code %> |
                        <b>Max Unit Limit: </b><%= feature.max_unit_limit %> |
                        <b>Unit Price: </b> $<%= feature.unit_price %> |
                        <b>Link to: </b><%= link_to 'Details', feature_path(feature) %> | 
                        <% if current_user.has_role? :manager %>
                            <%= link_to 'Edit', edit_feature_path(feature) %> |
                            <%= link_to 'Delete', feature_path(feature), method: :delete %>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </li>

    </ul>


    <h5 class="mt-3">
        <%= link_to 'Back', plans_path %> | 
        <% if current_user.has_role? :manager %>
            <%= link_to 'edit', edit_plan_path(@plan) %> | 
            <%= link_to 'delete', @plan, method: :delete %>
        <% else %>
        <%= link_to 'Subscribe Now', plan_subscriptions_path(@plan), method: :post, class: 'btn btn-success' %>
        <% end %>
    </h5>
</div>

app/views/shared/_field_errors.html.erb
<% if resource.errors[field].any? %>
    <ul class="errors">
      <% resource.errors[field].each do |message| %>
        <li><%= field.to_s.capitalize %> <%= message %></li>
      <% end %>
    </ul>    
<% end %>

app/views/shared/_notices_alerts.html.erb
<% if notice.present? %>
    <div class="alert alert-success" role="alert">
        <%= notice %>
    </div>
<% end %>
<% if alert.present? %>
    <div class="alert alert-danger" role="alert">
        <%= alert %>
    </div>
<% end %>